from __future__ import annotations

import json


class MockAIClient:
    def __init__(self, provider: str):
        self.provider = provider

    async def generate(self, prompt: str, symbol: str, timeout_seconds: int) -> str:
        payload = {
            "provider": self.provider,
            "symbol": symbol,
            "summary": f"Mock analysis for {symbol} generated by {self.provider}.",
            "signal": "neutral",
            "confidence": 0.58,
            "key_points": [
                "Trend is range-bound in the short term.",
                "Watch volume changes for breakout confirmation.",
            ],
            "timeout_seconds": timeout_seconds,
        }

        if self.provider == "claude":
            return f"```json\n{json.dumps(payload)}\n```"
        if self.provider == "grok":
            return f"Analysis draft:\n{json.dumps(payload)}\nEOF"
        return json.dumps(payload)
